### PR TITLE
Fix: rename src. Skipped scons warning causes compilation error

### PR DESCRIPTION
**Pull request by whplh**
Maybe handle  this type  of scons warning more strictly:
> scons: warning: Ignoring missing SConscript 'modules/arcore/SCsub'

### CODE REVIEW

**Comment by BastiaanOlij** [comment]
Bugger, I always make that mistake when I'm on Windows..

**Comment by BastiaanOlij** [comment]
I took this along in rebasing today, so not merging it. Can you check if it is working properly for you now?

**Comment by whplh** [comment]
@BastiaanOlij 
Looks good with:
 scons p=android -j3 target=release_debug android_arch=arm64v8
With: 
 scons p=android -j3 target=release_debug android_arch=armv7
Only debug apk gets build. Have to build 
 scons p=android -j3 target=release android_arch=armv7
separately to get the release.
It should build both release and debug apk's with release_debug option right?

**Comment by whplh** [comment]
Hmm,
just checked debug.apk with  android_arch=armv7
and I get
```
 META-INF/MANIFEST.MF
lib/armeabi-v7a/libc++_shared.so
lib/armeabi-v7a/libgodot_android.so

Resource table:
Package Groups (0)

No AndroidManifest.xml found.

```

**Comment by whplh** [comment]
Hmm my bad.
When switching architectures  
```
gradlew clean is need... otherwise the export of the Manifest breaks...

```
Sry I'm very new to Android
So the version of this brach yesteday was probably fine too...

**Comment by BastiaanOlij** [comment]
No, release_debug is purely a debug build, I have no idea what the exact difference between debug and release_debug is. 
You need to run scons with target=release to get the release builds.

My experience with android is pretty limited too so its all confusing the heck out of me. I'm going to try the gradlew clean because I'm still not getting the manifest either

**Pull request closed without merging**
